<?xml version="1.0"?>
<!--
Copyright (c) 2018, I3D Robotics Ltd.
Edited: 2019, Marti Morta Garriga, Wood.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="deimos_camera" params="camera_name:=deimos en_mesh:=false en_imu:=false">

    <xacro:property name="height" value="0.038"/>
    <xacro:property name="width" value="0.10175"/>
    <xacro:property name="length" value="0.03242"/>
    <xacro:property name="baseline" value="0.06"/>
    <xacro:property name="img_w" value="742"/>
    <xacro:property name="img_h" value="480"/>
    <xacro:property name="mesh_file" value="package://i3dr_deimos/mesh/deimos.stl"/>
    <xacro:property name="mesh_offset_xyz" value="-0.008 0.002 0"/>
    <xacro:property name="mesh_offset_rpy" value="${pi/2} 0 ${pi/2}"/>
    <xacro:property name="box_offset_xyz" value="0 0 0"/>
    <xacro:property name="box_offset_rpy" value="0 0 0"/>
    <xacro:property name="fov_rad" value="${62.8 * pi/180.0}"/>
    <xacro:property name="sim_w" value="${img_w/1}"/>
    <xacro:property name="sim_h" value="${img_h/1}"/>
    <xacro:property name="sim_rate" value="1"/>

    <material name="darkgrey">
        <color rgba= "0.1 0.1 0.1 1.0"/>
    </material>

    <link name="${camera_name}_cameraLeft_optical" />
    <link name="${camera_name}_cameraRight_optical" />
    <link name="${camera_name}_cameraLeft" />
    <link name="${camera_name}_cameraRight" />

    <link name="${camera_name}_depth_optical_frame" />

    <link name="${camera_name}_base_link" />

    <link name="${camera_name}_mount_base_link" />

    <xacro:if value="${(en_imu == 'true')}">
        <link name="${camera_name}_imu_link"/>
    </xacro:if>

    <link name="${camera_name}_mount_point_1"/>
    <link name="${camera_name}_mount_point_2"/>

    <link name="${camera_name}_probe_mount"/>

    <link name="${camera_name}_center">
        <pose>0 0 0 0 0 0</pose>

        <inertial>
            <mass value="0.11"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
        </inertial>

        <collision name="${camera_name}_center_collision">
            <geometry>
                <box size="${length} ${width} ${height}"/>
            </geometry>
        </collision>

        <visual>
            <xacro:if value="${(en_mesh == 'true')}">
                <origin xyz="${mesh_offset_xyz}" rpy="${mesh_offset_rpy}"/>
            </xacro:if>
            <xacro:if value="${(en_mesh == 'false')}">
                <origin xyz="${box_offset_xyz}" rpy="${box_offset_rpy}"/>
            </xacro:if>
            <geometry>
                <xacro:if value="${(en_mesh == 'true')}">
                    <mesh filename="${mesh_file}"/>
                </xacro:if>
                <xacro:if value="${(en_mesh == 'false')}">
                    <box size="${length} ${width} ${height}"/>
                </xacro:if>
            </geometry>
            <material name="darkgrey"/>
        </visual>
    </link>

    <xacro:if value="${(en_imu == 'true')}">
        <joint name="${camera_name}_imu_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
            <parent link="${camera_name}_base_link" />
            <child link="${camera_name}_imu_link" />
        </joint>
        <joint name="${camera_name}_imu_mount_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
            <parent link="${camera_name}_base_link" />
            <child link="${camera_name}_mount_base_link" />
        </joint>
    </xacro:if>
    <xacro:if value="${(en_imu == 'false')}">
        <joint name="${camera_name}_imu_mount_joint" type="fixed">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <parent link="${camera_name}_base_link" />
            <child link="${camera_name}_mount_base_link" />
        </joint>
    </xacro:if>

    <joint name="${camera_name}_right_camera_joint" type="fixed">
        <parent link="${camera_name}_center"/>
        <child link="${camera_name}_cameraRight"/>
        <origin xyz="0 ${-0.06/2}  0" rpy="0 0 0" />
    </joint>

    <joint name="${camera_name}_left_camera_joint" type="fixed">
        <parent link="${camera_name}_center"/>
        <child link="${camera_name}_cameraLeft"/>
        <origin xyz="0 ${0.06/2}  0" rpy="0 0 0" />
    </joint>

    <joint name="${camera_name}_left_optical_joint" type="fixed">
        <parent link="${camera_name}_cameraLeft"/>
        <child link="${camera_name}_cameraLeft_optical"/>
        <!-- Correct for the optical frame orientation -->
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${(-pi/2)}" />
    </joint>

    <joint name="${camera_name}_right_optical_joint" type="fixed">
        <parent link="${camera_name}_cameraRight"/>
        <child link="${camera_name}_cameraRight_optical"/>
        <!-- Correct for the optical frame orientation -->
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${(-pi/2)}" />
    </joint>

    <joint name="${camera_name}_depth_optical_joint" type="fixed">
        <parent link="${camera_name}_cameraLeft_optical"/>
        <child link="${camera_name}_depth_optical_frame"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <joint name="${camera_name}_mount_center_joint" type="fixed">
        <parent link="${camera_name}_mount_base_link"/>
        <child link="${camera_name}_center"/>
        <origin xyz="0 0 0" rpy="0 0 ${-pi/2}" />
    </joint>

    <joint name="${camera_name}_probe_mount_joint" type="fixed">
        <parent link="${camera_name}_mount_base_link"/>
        <child link="${camera_name}_probe_mount"/>
        <origin xyz="${0} 0 ${0}" rpy="0 0 0" />
    </joint>

    <joint name="${camera_name}_mount_point_1_joint" type="fixed">
        <parent link="${camera_name}_mount_base_link"/>
        <child link="${camera_name}_mount_point_1"/>
        <origin xyz="${(0.03/2)-0.002} -0.007 ${-0.038/2}" rpy="0 0 0" />
    </joint>
    <joint name="${camera_name}_mount_point_2_joint" type="fixed">
        <parent link="${camera_name}_mount_base_link"/>
        <child link="${camera_name}_mount_point_2"/>
        <origin xyz="${(-0.03/2)-0.002} -0.007 ${-0.038/2}" rpy="0 0 0" />
    </joint>

    <!-- Simulate stereo camera using gazebo -->
    <xacro:macro name="optical_camera" params="name offset fov_rad:=^ sim_w:=^ sim_h:=^">
        <camera name="${name}">
            <pose>0 ${offset} 0 0 0 0</pose>
            <horizontal_fov>${fov_rad}</horizontal_fov>
            <image>
                <width>${sim_w}</width>
                <height>${sim_h}</height>
                <format>B8G8R8</format>
            </image>
            <clip>
                <near>0.02</near>
                <far>300</far>
            </clip>
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.007</stddev>
            </noise>
      </camera>
    </xacro:macro>
    <gazebo reference="${camera_name}_cameraLeft">
      <sensor type="multicamera" name="stereo_camera">
        <update_rate>${sim_rate}</update_rate> <!-- reality 60fps on USB3-->
        <optical_camera name="left" offset="0" />
        <optical_camera name="right" offset="${-baseline}" />
        <plugin name="stereo_camera_controller" filename="libgazebo_ros_multicamera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>${sim_rate}</updateRate>
          <cameraName>${camera_name}</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>${camera_name}_cameraLeft_optical</frameName>
          <hackBaseline>${baseline}</hackBaseline>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>
      </sensor>
    </gazebo>

    <!-- Simulate IMU using gazebo -->
    <xacro:if value="${(en_imu == 'true')}">
        <gazebo reference="${camera_name}_imu_link">
            <gravity>true</gravity>
            <sensor name="imu_sensor" type="imu">
            <always_on>true</always_on>
            <update_rate>100</update_rate>
            <visualize>true</visualize>
            <topic>__default_topic__</topic>
            <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
                <topicName>imu</topicName>
                <bodyName>${camera_name}_imu_link</bodyName>
                <updateRateHZ>10.0</updateRateHZ>
                <gaussianNoise>0.0</gaussianNoise>
                <xyzOffset>0 0 0</xyzOffset>
                <rpyOffset>0 0 0</rpyOffset>
                <frameName>${camera_name}_imu_link</frameName>
                <initialOrientationAsReference>false</initialOrientationAsReference>
            </plugin>
            <pose>0 0 0 0 0 0</pose>
            </sensor>
        </gazebo>
    </xacro:if>

    <!-- Attach material to gazebo object -->
    <gazebo reference="${camera_name}_center">
        <gravity>true</gravity>
        <material>Gazebo/DarkGrey</material>
    </gazebo>

  </xacro:macro>

</robot>
