<?xml version="1.0"?>
<!--
Copyright (c) 2019, I3D Robotics Ltd.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="i3dr_stereo_camera" params="camera_name baseline toe_in width height length image_format:=RGB8 image_height:=640 image_width:=480 hfov:=1.579 focus_near:=0 focus_far:=100 camera_offset_x:=0 camera_offset_y:=0 camera_offset_z:=0 mount_offset_x:=0 mount_offset_y:=0 mount_offset_z:=0 r:=1 g:=0 b:=0 a:=1">
        <link name="${camera_name}_cameraLeft_optical" />
        <link name="${camera_name}_cameraRight_optical" />
        <link name="${camera_name}_cameraLeft" />
        <link name="${camera_name}_cameraRight" />

        <link name="${camera_name}_base_link" />

        <link name="${camera_name}_center">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${width} ${height} ${length}"/>
                </geometry>
                <material name="${camera_name}_camera_colour">
                    <color rgba="${r} ${g} ${b} ${a}"/>
                </material>
            </visual>
        </link>

        <joint name="${camera_name}_right_camera_joint" type="fixed">
            <parent link="${camera_name}_center"/>
            <child link="${camera_name}_cameraRight"/>
            <origin xyz="${camera_offset_x} -${(baseline/2)+camera_offset_y} ${camera_offset_z}" rpy="0 0 0" />
        </joint>

        <joint name="${camera_name}_left_camera_joint" type="fixed">
            <parent link="${camera_name}_center"/>
            <child link="${camera_name}_cameraLeft"/>
            <origin xyz="${camera_offset_x} ${(baseline/2)+camera_offset_y} ${camera_offset_z}" rpy="0 0 0" />
        </joint>

        <joint name="${camera_name}_left_optical_joint" type="fixed">
            <parent link="${camera_name}_cameraLeft"/>
            <child link="${camera_name}_cameraLeft_optical"/>
            <!-- Correct for the optical frame orientation -->
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${(-pi/2)-toe_in}" />
        </joint>

        <joint name="${camera_name}_right_optical_joint" type="fixed">
            <parent link="${camera_name}_cameraRight"/>
            <child link="${camera_name}_cameraRight_optical"/>
            <!-- Correct for the optical frame orientation -->
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${(-pi/2)+toe_in}" />
        </joint>

        <sensor name="${camera_name}_right_camera_sensor" update_rate="60">
            <parent link="${camera_name}_cameraRight_optical"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <camera>
                <image width="${image_width}" height="${image_height}" hfov="${hfov}" format="${image_format}" near="${focus_near}" far="${focus_far}"/>
            </camera>
        </sensor>

        <joint name="${camera_name}_mount_center_joint" type="fixed">
            <parent link="${camera_name}_base_link"/>
            <child link="${camera_name}_center"/>
            <origin xyz="${mount_offset_x} ${mount_offset_y} ${(length/2)+mount_offset_z}" rpy="0 0 0" />
        </joint>

    </xacro:macro>
</robot>